
    create table Canchas (
        cancha_id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        tieneIluminacion boolean,
        color_id bigint,
        primary key (cancha_id)
    )

    create table Color (
        id bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (id)
    )

    create table Fabricante (
        idFabricante bigint generated by default as identity (start with 1),
        nombreFabricante varchar(255),
        primary key (idFabricante)
    )

    create table Inscripcion (
        inscripcionId bigint generated by default as identity (start with 1),
        jugador_jugadorId bigint,
        paleta_paletaId bigint,
        primary key (inscripcionId)
    )

    create table Jugador (
        tipo_jugador varchar(31) not null,
        jugadorId bigint generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(255),
        fechaNacimiento timestamp,
        nombre varchar(255),
        telefono varchar(255),
        paleta_paletaId bigint,
        primary key (jugadorId)
    )

    create table JugadorAmateur (
        jugadorId bigint not null,
        primary key (jugadorId)
    )

    create table JugadorProfesional (
        altura integer not null,
        cantidadVictoriasEnTorneos integer not null,
        peso integer not null,
        jugadorId bigint not null,
        primary key (jugadorId)
    )

    create table JugadorSemiProfesional (
        altura integer not null,
        peso integer not null,
        jugadorId bigint not null,
        primary key (jugadorId)
    )

    create table Paleta (
        paletaId bigint generated by default as identity (start with 1),
        grosor integer,
        nombre varchar(255),
        color_id bigint,
        primary key (paletaId)
    )

    create table Reserva (
        reservaId bigint generated by default as identity (start with 1),
        fechaHoraFin timestamp,
        fechaHoraInicio timestamp,
        colorCancha_id bigint,
        cancha_id bigint,
        primary key (reservaId)
    )

    create table Reserva_Inscripcion (
        Reserva_reservaId bigint not null,
        inscripciones_inscripcionId bigint not null
    )

    alter table Reserva_Inscripcion 
        add constraint UK_8dgahsymd6o1ejltvg107rsl  unique (inscripciones_inscripcionId)

    alter table Canchas 
        add constraint FK_aksdj4kqk9g05t05g7b2bjmpn 
        foreign key (color_id) 
        references Color

    alter table Inscripcion 
        add constraint FK_n43owf2g795j7uix8qjlakr56 
        foreign key (jugador_jugadorId) 
        references Jugador

    alter table Inscripcion 
        add constraint FK_cdg91mgg3v1sm5y9d7xbky1sy 
        foreign key (paleta_paletaId) 
        references Paleta

    alter table Jugador 
        add constraint FK_6ymdr4mb7gokbn9cghiuuexo8 
        foreign key (paleta_paletaId) 
        references Paleta

    alter table JugadorAmateur 
        add constraint FK_dbi7yl4tdsjjtfj3mv97ob3hr 
        foreign key (jugadorId) 
        references Jugador

    alter table JugadorProfesional 
        add constraint FK_318xcwg4y870hkv8b5bqjx5k4 
        foreign key (jugadorId) 
        references Jugador

    alter table JugadorSemiProfesional 
        add constraint FK_8u37vpdq7qgtr2imep4hqbno5 
        foreign key (jugadorId) 
        references Jugador

    alter table Paleta 
        add constraint FK_7j6gn3e0x0t337q9254dvbx7g 
        foreign key (color_id) 
        references Color

    alter table Reserva 
        add constraint FK_dw46e3722aq5tbv2cjldf0tie 
        foreign key (colorCancha_id) 
        references Color

    alter table Reserva 
        add constraint FK_dvj3g2srskhu0a8urixuvn7bc 
        foreign key (cancha_id) 
        references Canchas

    alter table Reserva_Inscripcion 
        add constraint FK_8dgahsymd6o1ejltvg107rsl 
        foreign key (inscripciones_inscripcionId) 
        references Inscripcion

    alter table Reserva_Inscripcion 
        add constraint FK_8md05lt4y84plqk27eltc2rhr 
        foreign key (Reserva_reservaId) 
        references Reserva
