
    create table Cancha (
        CANCHA_ID bigint generated by default as identity (start with 1),
        nombre varchar(255),
        tieneIluminacion boolean,
        color_colorId bigint,
        primary key (CANCHA_ID)
    )

    create table Cancha_Reserva (
        Cancha_CANCHA_ID bigint not null,
        reservas_reservaId bigint not null
    )

    create table Color (
        colorId bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (colorId)
    )

    create table Fabricante (
        idFabricante bigint generated by default as identity (start with 1),
        nombreFabricante varchar(255),
        primary key (idFabricante)
    )

    create table Inscripcion (
        inscripcionId bigint generated by default as identity (start with 1),
        jugador_jugadorId bigint,
        paleta_paletaId bigint,
        primary key (inscripcionId)
    )

    create table Jugador (
        jugadorId bigint generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(255),
        fechaNacimiento timestamp,
        nombre varchar(255),
        telefono varchar(255),
        paleta_paletaId bigint,
        primary key (jugadorId)
    )

    create table Paleta (
        paletaId bigint generated by default as identity (start with 1),
        grosor integer,
        nombre varchar(255),
        color_colorId bigint,
        primary key (paletaId)
    )

    create table Reserva (
        reservaId bigint generated by default as identity (start with 1),
        fechaHoraFin varbinary(255),
        fechaHoraInicio varbinary(255),
        color_colorId bigint,
        primary key (reservaId)
    )

    create table Reserva_Inscripcion (
        Reserva_reservaId bigint not null,
        inscripciones_inscripcionId bigint not null
    )

    alter table Cancha_Reserva 
        add constraint UK_6dp79u0fxp2xnjcvd7mmxm2ne  unique (reservas_reservaId)

    alter table Reserva_Inscripcion 
        add constraint UK_8dgahsymd6o1ejltvg107rsl  unique (inscripciones_inscripcionId)

    alter table Cancha 
        add constraint FK_3ky9n2unfp35x2yoxwbylg3wu 
        foreign key (color_colorId) 
        references Color

    alter table Cancha_Reserva 
        add constraint FK_6dp79u0fxp2xnjcvd7mmxm2ne 
        foreign key (reservas_reservaId) 
        references Reserva

    alter table Cancha_Reserva 
        add constraint FK_kbwhgtkfk5r6ax57rox0tkxrh 
        foreign key (Cancha_CANCHA_ID) 
        references Cancha

    alter table Inscripcion 
        add constraint FK_n43owf2g795j7uix8qjlakr56 
        foreign key (jugador_jugadorId) 
        references Jugador

    alter table Inscripcion 
        add constraint FK_cdg91mgg3v1sm5y9d7xbky1sy 
        foreign key (paleta_paletaId) 
        references Paleta

    alter table Jugador 
        add constraint FK_6ymdr4mb7gokbn9cghiuuexo8 
        foreign key (paleta_paletaId) 
        references Paleta

    alter table Paleta 
        add constraint FK_2otk03i1idirrjepcu5i1fc3t 
        foreign key (color_colorId) 
        references Color

    alter table Reserva 
        add constraint FK_d5lrxidd3m082i01l1igus0l5 
        foreign key (color_colorId) 
        references Color

    alter table Reserva_Inscripcion 
        add constraint FK_8dgahsymd6o1ejltvg107rsl 
        foreign key (inscripciones_inscripcionId) 
        references Inscripcion

    alter table Reserva_Inscripcion 
        add constraint FK_8md05lt4y84plqk27eltc2rhr 
        foreign key (Reserva_reservaId) 
        references Reserva
